# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-22 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
